- hosts: all
  become: yes
  vars:
    - message: "Greetings from Cloudify!"
    - port: "80"
  tasks:
    - name: Install EPEL
      package:
        name: epel-release
        state: present

    - name: install nginx
      package:
        name: nginx
        state: present

    - name: create www directory
      file:
        path: /var/www/app
        recurse: yes
        state: directory
        mode: '0775'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: create index.html
      template:
        src: index.j2
        dest: /var/www/app/index.html

    - name: Copy NGINX base config
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644

    - name: copy nginx site.conf
      template:
        src: site.conf.j2
        dest: /etc/nginx/conf.d/app.conf
        owner: root
        group: root
        mode: '0644'

    - name: restart nginx
      service:
        name: nginx
        state: restarted
